### ISSUE TITLE
Providing get_params and set_params to make cubist work in a pipeline

### ISSUE THREAD

**Issue by ritviksahajpal** [GeoscienceAustralia/uncover-ml#36]
Thanks for an excellent library. I had a query regarding using uncover-ml cubist functionality in a scikit pipeline. It seems like that it cannot be used in a pipeline because the functions `set_params` and `get_params` have not been implemented as per here: http://danielhnyk.cz/creating-your-own-estimator-scikit-learn/

Can you provide those? I am happy to submit a pull request as well if it is ok with the authors? Enabling pipeline usage will help with hyperparameter optimization as well.

thanks!

**Comment by basaks** [comment]
Hi @ritviksahajpal, `cubist` works with the `uncoverml` pipeline. I have just tested it. We call the `cubist` binary using a system call in python. I can add some geotifs and a configuration file that worked for me. Will that help?

Any PR is welcome to make this class fully `scikit-learn` compatible is most welcome.

**Comment by basaks** [comment]
@ritviksahajpal I have added some data in `configs/data/` and you can use the `configs/cubist.yaml` to use that data as a test. 

Change the path to the data and then use:

```
uncoverml learn /path/to/cubist.yaml -p 4
uncoverml predict /path/to/cubist.model -p 4
```

**Comment by ritviksahajpal** [comment]
thanks @basaks ! I will check these and update you
