### ISSUE TITLE
Analyse the AEM datasets for machine learning

### ISSUE THREAD

**Issue by niketchhajed** [GeoscienceAustralia/uncover-ml#39]
Analyse the AEM datasets for converting to a format and quality that can be fed to a regression/classification algorithm.

**Comment by niketchhajed** [comment]
The analysis of the AEM survey dataset revealed very high correlation between 3 of the 5 co-variates. Also, a couple of other non-AEM covariates were found to correlate differently.

**Comment by zhang01GA** [comment]
That's very interesting. good work thanks Niket

**Comment by niketchhajed** [comment]
Closing the completed task.
