### ISSUE TITLE
uncoverml pre-req and setup issues for new user

### ISSUE THREAD

**Issue by s-m-t-c** [GeoscienceAustralia/uncover-ml#40]
# **Uncover ML - set up errors**

**Current**

Module / python egg related error

- Full output

[uncovermlmodulerror.txt](https://github.com/GeoscienceAustralia/uncover-ml/files/1782838/uncovermlmodulerror.txt)

- sample output

```
virtualenvwrapper.user_scripts could not run "/g/data/ge3/john/venvs/preactivate": [Errno 8] Exec format error
mpirun: WARNING: unable to determine OpenMPI version of uncoverml, runtime version may be incompatible
```
```
File "/g/data1a/ge3/john/venvs/catboost/bin/uncoverml", line 11, in <module>
    load_entry_point('uncover-ml', 'console_scripts', 'uncoverml')()
```

**Solved**

- `$ py.test ~/uncover-ml/tests/` generates error:
`ImportError: No module named 'mpi4py' `

Tried `$ pip install -v --no-binary :all: --user mpi4py` as a solution but generates error (this worked for previous missing module errors).

Full output here: [uncovermlerrortext.txt](https://github.com/GeoscienceAustralia/uncover-ml/files/1769822/uncovermlerrortext.txt)

- Automating the loading of python modules through .profile generates error, success when manually installed via 'Module load'
`python3/3.4.3(2):ERROR:150: Module 'python3/3.4.3' conflicts with the currently loaded module(s) 'python3/3.4.3-matplotlib'`
`python3/3.4.3(2):ERROR:102: Tcl command execution failed: source /opt/Modules/extensions/extensions.tcl`

- Could not copy the github repository due to a 'public key' error
    - Generated a new SSH private key 'id_rsa' and copied it into the appropriate hidden folder in my NCI home .ssh (using mobaxtherm sftp)
    - Changed the permissions to 400 on my ssh folder then added to ssh agent
```
chmod 400 ~/.ssh/id_rsa
ssh-add ~/.ssh/id_rsa
```

- Running test indicates missing module `$ py.test ~/uncover-ml/tests/`
```
import shapefile as shp
ImportError: No module named 'shapefile'
```

 Solved by installing 'shapefile' with:
 `pip install -v --no-binary :all: --user pyshp`

**Comment by basaks** [comment]
```
```
virtualenvwrapper.user_scripts could not run "/g/data/ge3/john/venvs/preactivate": [Errno 8] Exec format error
mpirun: WARNING: unable to determine OpenMPI version of uncoverml, runtime version may be incompatible
```
```
File "/g/data1a/ge3/john/venvs/catboost/bin/uncoverml", line 11, in <module>
    load_entry_point('uncover-ml', 'console_scripts', 'uncoverml')()
```

```
What are you trying to do?
