### ISSUE TITLE
Add metadata to prediction geotifs

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/uncover-ml#51]
Attach  the following meta data to the model prediction  - 

1. the list of covariates
2. yaml configuration
3. performance measures
4. git hash from the uncoverml codebase
5. name of the output predictions mode names?

**Comment by basaks** [comment]
Best place to do this is probably [where the output rasters are defined in the `ImageWriter` class](https://github.com/GeoscienceAustralia/uncover-ml/blob/master/uncoverml/geoio.py#L278).

**Comment by basaks** [comment]
Actually rasterio has an functionality [update_tag](https://rasterio.readthedocs.io/en/stable/topics/tags.html#writing-tags), which seem like can do the job quite well.

https://rasterio.readthedocs.io/en/stable/topics/tags.html#writing-tags

**Comment by brenmous** [comment]
Fei has a written code that writes metadata to a text file. If it's desired to be embedded in the geotiffs this can be done later.
