### ISSUE TITLE
Learn and predict using corner coordinates/map extents

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/uncover-ml#52]
It is highly desirable from disc management perspective, and also when the virtual geophysics lab come into play to be able to 

1. specify the area of interest (from the national dataset)
2. learn and predict

More specifically, following `gdalwarp` we want to have something similar to the following in the config file which should be used for learn and predict jobs:

> extents: xmin ymin xmax ymax

Both the target `shapefile` and the input raster covariates should use the `extents`.

**Comment by brenmous** [comment]
[covariates](https://github.com/GeoscienceAustralia/uncover-ml/blob/develop/uncoverml/geoio.py#L176) and [targets](https://github.com/GeoscienceAustralia/uncover-ml/blob/develop/uncoverml/geoio.py#L317)
