### ISSUE TITLE
Error in installation .“[WinError 193] %1 not a valid Win32 application ”

### ISSUE THREAD

**Issue by Mosessun** [GeoscienceAustralia/uncover-ml#53]
My Windows environment is win10, my python edition is 3.7.3 with 64- bit. But when I use "python setup.py install" to installing, I met the error:"[WinError 193] %1 not a valid Win32 application". How do I solve it?

**Comment by basaks** [comment]
Hi @Mosessun, Thank you for your interest. We don't support windows at this point.
