### ISSUE TITLE
Move preprocessing inside uncoverml?

### ISSUE THREAD

**Issue by lmccalman** [GeoscienceAustralia/uncover-ml#8]
Otherwise if it's a top-level module, it should be a general preprocessing package! (It seems specifically for uncoverml)

**Comment by lmccalman** [comment]
The answer here appears to be 'sort of' -- probably the best place for this stuff is a separate repo - but at the moment it is intertwined with uncoverml so would require a refactor to achieve

**Comment by basaks** [comment]
@lmccalman The only reason this is `intertwined` with the rest of uncoverml is that the resampling code can be used on the fly during the data prep stage. 

We don't necessairly need to support on the fly resampling of shapefiles, and then it will make sense to refactor the preprocessing step out of the main `uncoverml` directory, and we can simply provide an executable for resampling. It will still be easier to maintain the resampling functionality within the repo I think.
